apiVersion: v2
appVersion: 0.0.0.0
dependencies:
- condition: postgresql.bundled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: ^12.1.6
- condition: memcached.bundled
  name: memcached
  repository: oci://registry-1.docker.io/bitnamicharts
  version: ^6.3.2
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: ^2.2.2
description: A Helm chart for running MarvalProject via Kubernetes
home: https://marvalglobal.com
icon: https://marvalglobal.com/assets/templates/images/svg/marval-logo-letters.svg
name: marvalproject
type: application
version: 11.4.2
