dockerconfig: #{global:docker:config}
global:
  imagePullSecrets: 
    - marvalprojects-acr-pull-secret

nodeSelector:
  applications: "linuxapps"

persistence:
  enabled: false

ingress:
  enabled: true
  letsEncryptUrl: https://acme-v02.api.letsencrypt.org/directory
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "1024k"
    nginx.ingress.kubernetes.io/proxy-buffering: 'on'
    nginx.ingress.kubernetes.io/proxy-buffers-number: '4'
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-mode: "persistent"
    nginx.ingress.kubernetes.io/session-cookie-path: "/"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "360"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "360"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    ##nginx.ingress.kubernetes.io/limit-rps: 100
    cert-manager.io/issuer: marvalprojects-letsencrypt
    nginx.ingress.kubernetes.io/location-snippets: |
      proxy_cookie_path       / "/; Secure";
      proxy_cache_revalidate on;
      proxy_cache_min_uses 3;
      proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
      proxy_cache_background_update on;
      proxy_cache_lock on;
      proxy_cache_methods GET HEAD;        
      add_header X-Cache-Status $upstream_cache_status;
  host: "#{global:ingress:hostname}.#{global:ingress:domain}"
  path: /Projects
  pathType: "Prefix"
  tls:    
    enabled: true
    secretName: "marvalprojects-tls-secret"

image:
  registry: "ukcomarvalnextgen.azurecr.io"
  repository: "marvalproject"
  imagePullPolicy: "Always"
  tag: "1.0.0.32215"

memcached: 
  bundled: true
  image:
    repository: bitnamilegacy/memcached
    tag: 1.6.24-debian-12-r0
  nodeSelector:
    applications: "linuxapps"

web:
  nodeSelector:
    applications: "linuxapps"

worker:
  nodeSelector:
    applications: "linuxapps"
 
seeder:
  nodeSelector:
    applications: "linuxapps"

strategy:  
  type: "Recreate"

cron:
  enabled: #{cron:enabled}  
  environment:
    IMAP_HOST: "#{cron:environment:IMAP_HOST}"
    IMAP_USERNAME: "#{cron:environment:IMAP_USERNAME}"
    IMAP_PASSWORD: "#{cron:environment:IMAP_PASSWORD}"
    IMAP_PORT: #{cron:environment:IMAP_PORT}"

openproject:
  admin_user:
    password: "#{openproject:admin_user:password}"
    password_reset: "#{openproject:admin_user:password_reset}"
    name: "#{openproject:admin_user:name}"
    mail: "#{openproject:admin_user:mail}"

s3:
  enabled: true
  auth:
    accessKeyId: #{s3:auth:accessKeyId}
    secretAccessKey: #{s3:auth:secretAccessKey}
  region: #{s3:region}
  bucketName: #{s3:bucketName}

postgresql:  
  bundled: false
  connection:
    host: #{postgresql:connection:host}
    port: #{postgresql:connection:port}
  auth:
    username: "#{postgresql:auth:username}"
    database: "#{postgresql:auth:database}"
    password: "#{postgresql:auth:password}"
    postgresPassword: "#{postgresql:auth:postgresPassword}"